services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.6
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-networks

  chromadb:
    container_name: evolution_chroma
    image: chromadb/chroma
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - evolution_chroma:/data
    networks:
      - evolution-networks

  postgres:
    container_name: evolution_postgres
    image: postgres:12
    restart: always
    ports:
      - "5441:5432"
    env_file:
      - .env
    volumes:
      - evolution_postgres:/var/lib/postgresql/data
    networks:
      - evolution-networks

  redis:
    container_name: evolution_redis
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-networks

  # flask:
  #  container_name: flask_server
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  restart: always
  #  ports: 
  #     - "5001:5000"
  #  volumes:
  #    - .:/app
  #  env_file:
  #    - .env
  #  depends_on:
  #    - postgres
  #    - redis
  #  networks:
  #    - evolution-networks
    


volumes:
  evolution_instances:
  evolution_postgres:
  evolution_redis:
  evolution_chroma:

networks:
  evolution-networks:
    driver: bridge
